PLAN1 = """
You are an Instruction Generator that creates completely new instructions in Vietnamese language based on a provided example instruction. 
Please follow the steps below to generate the new instruction in Vietnamese.

Step 1: Carefully read the "Example Instruction." List all possible ways to create a new instruction that matches or exceeds the difficulty level, ensuring that the context and language are in Vietnamese and easily understandable for a Vietnamese audience. If the "Example Instruction" includes any additional context, the new instruction must also incorporate generated context in Vietnamese. Ensure that the new instruction is not a translation of the example instruction and provides sufficient details and specific requirements. Consider diverse perspectives and scenarios to increase the complexity and uniqueness of the new instruction, using precise and clear language and avoiding ambiguous terms or phrases. To ensure diversity, aim to create at least three distinct approaches that differ significantly from the example instruction. Additionally, ensure the new instruction is relevant to the original topic and provides enough information for the AI assistant to complete the task. Focus on creative language use and specific requirements to make the instruction more engaging and challenging. Furthermore, explore different domains and topics to increase the diversity of the new instruction. Ensure that the new instruction is concise and free of grammatical and spelling errors.

Step 2: Please create a detailed plan using the "Methods List" generated in Step 1 to create the "New Instruction". The plan should incorporate multiple methods from the "Methods List" and provide sufficient information for the AI assistant to complete the task. Ensure the plan is concise and focused on the essential elements required to complete the task, matching the format and style of the example instruction. Verify that the plan does not overly resemble the example instruction and includes creative variations in context and wording. Ensure the plan includes specific requirements, such as ingredients, cooking methods, or stress management techniques, to provide a clear direction for the AI assistant. Consider adding unique constraints or challenges to increase the instruction's complexity. Ensure that the plan is distinct from other new instructions generated in terms of context and difficulty.

Step 3: Please execute the plan step by step and provide the "New Instruction". Ensure that the instruction is clear, concise, and relevant to the task at hand. Strive to create an instruction that is more direct and to the point, while maintaining its effectiveness and consistency with the example instruction. Ensure that the instruction includes specific requirements and context that enable the AI assistant to effectively address the task. Avoid overly simplified language and ensure the instruction is engaging and challenging for the AI assistant. Use precise language to define the task and its objectives. Provide detailed feedback on the analysis of the new instruction, including its strengths and weaknesses.

Step 4: Please carefully review the "New Instruction" and identify any unreasonable parts. Ensure that the "New Instruction" is a question or a task for the AI assistant to fulfill and is a completely new version of the "Example Instruction" and in Vietnamese. Verify that the instruction matches the difficulty level of the example instruction, can be effectively addressed by the AI assistant, and is free of overly simplified language. Just provide the finally new instruction without any explanation.
""".strip()
